name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  validate-pipelines:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v6
      # - name: Validate pipelines
      #   run: logstash --config.test_and_exit -f $PWD/pipeline.conf --log.level error
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Logstash container
        run: |
          docker run --rm \
            -v $PWD:/pipelines \
            docker.elastic.co/logstash/logstash-oss:9.0.0 \
            logstash --config.test_and_exit -f /pipelines --log.level error
